Repository mindenit/ui, pull requests merged in 2024-07, with the labels that each got.

#11 feat: add Avatar component
  .prettierrc
  src/components/Avatar/Avatar.stories.ts
  src/components/Avatar/TheAvatar.vue
  src/components/Avatar/index.ts
Labels: enhancement

#12 feat: add Alert component
  src/components/Alert/Alert.stories.ts
  src/components/Alert/AlertDescription.vue
  src/components/Alert/AlertTitle.vue
  src/components/Alert/TheAlert.vue
  src/components/Alert/index.ts
  src/components/Text/index.ts
  tsconfig.json
Labels: enhancement

#13 feat: add Badge component
  src/components/Badge/Badge.stories.ts
  src/components/Badge/TheBadge.vue
  src/components/Badge/index.ts
Labels: enhancement

#14 feat: add Pagination component
  src/components/Pagination/Pagination.stories.ts
  src/components/Pagination/ThePagination.vue
  src/components/Pagination/index.ts
Labels: enhancement

#16 fix: fix Pagination component styles
  src/components/Pagination/Pagination.stories.ts
  src/components/Pagination/ThePagination.vue
Labels: wontfix

#18 feat: add SearchField component
  src/assets/index.css
  src/components/SearchField/SearchField.stories.ts
  src/components/SearchField/SearchField.vue
  src/components/SearchField/index.ts
  src/components/TextField/TextFieldInput.vue
  src/components/TextField/index.ts
Labels: enhancement

#20 feat: add TagsField component
  src/App.vue
  src/components/TagsField/TagsField.stories.ts
  src/components/TagsField/TagsField.vue
  src/components/TagsField/index.ts
Labels: enhancement

#19 feat: create Accordion component
  src/components/Accordion/Accordion.stories.ts
  src/components/Accordion/AccordionItem.vue
  src/components/Accordion/AccordionRoot.vue
  src/components/Accordion/index.ts
  tailwind.config.js
Labels: bug, enhancement

#21 feat: add PinField component
  src/components/PinField/PinField.stories.ts
  src/components/PinField/PinField.vue
  src/components/PinField/index.ts
Labels: enhancement

#22 feat: add Tabs component
  src/assets/index.css
  src/components/TabMenu/TabMenu.stories.ts
  src/components/TabMenu/TabMenuContent.vue
  src/components/TabMenu/TabMenuList.vue
  src/components/TabMenu/TabMenuRoot.vue
  src/components/TabMenu/TabMenuTrigger.vue
  src/components/TabMenu/index.ts
Labels: enhancement

#24 feat: add Dialog component
  src/components/Dialog/Dialog.stories.ts
  src/components/Dialog/DialogBody.vue
  src/components/Dialog/DialogClose.vue
  src/components/Dialog/DialogContent.vue
  src/components/Dialog/DialogFooter.vue
  src/components/Dialog/DialogHeader.vue
  src/components/Dialog/DialogRoot.vue
  src/components/Dialog/DialogTrigger.vue
  src/components/Dialog/index.ts
  src/components/Form/FormLabel.vue
  tailwind.config.js
Labels: enhancement

#23 feat: add StepIndicator component
  package.json
  pnpm-lock.yaml
  src/components/StepIndicator/StepIndicator.stories.ts
  src/components/StepIndicator/StepIndicatorItem.vue
  src/components/StepIndicator/StepIndicatorRoot.vue
  src/components/StepIndicator/index.ts
Labels: enhancement

#25 feat: add TextArea component
  src/components/TextArea/TextArea.stories.ts
  src/components/TextArea/TextAreaInput.vue
  src/components/TextArea/TextAreaRoot.vue
  src/components/TextArea/index.ts
Labels: enhancement

#26 feat: add FileField component
  src/App.vue
  src/components/Button/index.ts
  src/components/FileField/FileField.stories.ts
  src/components/FileField/FileField.vue
  src/components/FileField/index.ts
  src/components/FileTrigger/FileTrigger.stories.ts
  src/components/FileTrigger/FileTrigger.vue
  src/components/FileTrigger/index.ts
  src/components/ImageField/ImageField.stories.ts
  src/components/ImageField/ImageField.vue
  src/components/ImageField/index.ts
Labels: enhancement

#27 feat: add Toast component
  src/components/Toast/TheToast.vue
  src/components/Toast/TheToaster.vue
  src/components/Toast/ToastAction.vue
  src/components/Toast/ToastClose.vue
  src/components/Toast/ToastDescription.vue
  src/components/Toast/ToastProvider.vue
  src/components/Toast/ToastTitle.vue
  src/components/Toast/ToastViewport.vue
  src/components/Toast/index.ts
  src/components/Toast/useToast.ts
Labels: enhancement
